// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0Ql_flqq_rf53ErUJI0nDuCUauufq94',
    appId: '1:2089029110:web:493ecf6036ffa749944bd7',
    messagingSenderId: '2089029110',
    projectId: 'extremecool-app',
    authDomain: 'extremecool-app.firebaseapp.com',
    storageBucket: 'extremecool-app.firebasestorage.app',
    measurementId: 'G-ZNDYER78ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzHWNLtNaFBBKBiRI-FtK-bbLV5WKTIE',
    appId: '1:2089029110:android:ee1f975aa1cb2614944bd7',
    messagingSenderId: '2089029110',
    projectId: 'extremecool-app',
    storageBucket: 'extremecool-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALaocLdIZ5ZhPpYFmLpzoYGp9uJOzOPUA',
    appId: '1:2089029110:ios:ee9084c418c8e3a8944bd7',
    messagingSenderId: '2089029110',
    projectId: 'extremecool-app',
    storageBucket: 'extremecool-app.firebasestorage.app',
    iosBundleId: 'com.extreme.user.app.extrememedicaluserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALaocLdIZ5ZhPpYFmLpzoYGp9uJOzOPUA',
    appId: '1:2089029110:ios:ee9084c418c8e3a8944bd7',
    messagingSenderId: '2089029110',
    projectId: 'extremecool-app',
    storageBucket: 'extremecool-app.firebasestorage.app',
    iosBundleId: 'com.extreme.user.app.extrememedicaluserapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj0Ql_flqq_rf53ErUJI0nDuCUauufq94',
    appId: '1:2089029110:web:c63ba391130f7613944bd7',
    messagingSenderId: '2089029110',
    projectId: 'extremecool-app',
    authDomain: 'extremecool-app.firebaseapp.com',
    storageBucket: 'extremecool-app.firebasestorage.app',
    measurementId: 'G-7PQRVZ3Y23',
  );
}
